name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main # ou 'master' selon ton branchement

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set Vite env variables
        run: |
          echo "VITE_ACTION_SECRET=${{ secrets.VITE_ACTION_SECRET }}" >> .env
          echo "VITE_ACTION_KEY=${{ secrets.VITE_ACTION_KEY }}" >> .env
          echo "VITE_DEV_MODE=false" >> .env

      - name: Build Vite project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
